Module3 task1
htmlacademy-adaptive/472465-sedona-25 pull request #4
Opened 2022-04-07 00:11 UTC by Anatoly230

Абсолютно запутался что делать.
1) не понимаю как подключать файлы - @import  элементы блок к блоку и выше по иерархии?
продублировал стили в стилевом файле, чтобы были результаты по данному заданию.
2) не понимаю какие отступы давать давать крупным сеточным элементам, но что ориентироваться - говорил про mobile first, но фактически толком его не обсуждали.
прошу отметить ошибки,  чтобы я их исправил.
Заранее спасибо!

2022-04-07 00:47 UTC, Anatoly230 commented
Абсолютно запутался что делать.

не понимаю как подключать файлы - https://github.com/import элементы блок к блоку и выше по иерархии?
продублировал стили в стилевом файле, чтобы были результаты по данному заданию.
не понимаю какие отступы давать давать крупным сеточным элементам, но что ориентироваться - говорил про mobile first, но фактически толком его не обсуждали.
прошу отметить ошибки, чтобы я их исправил.
Заранее спасибо!

2022-04-09 08:15 UTC, ValeryKrukovich requested changes

2022-04-09 08:15 UTC, ValeryKrukovich commented on source/sass/page/global.scss
> +  --die-color: #81b3d2;
При использовании препроцессора лучше используй переменные а не кастомные свойства нативного css. А то у тебя получается мешанина.

2022-04-09 10:45 UTC, Anatoly230 commented
поменял кастомные свойства на переменные scss, и сменил директорию с page/blocks на sass/blocks

2022-04-09 11:31 UTC, merged