Адаптивная сетка для главной страницы
htmlacademy-adaptive/472465-sedona-25 pull request #5
Opened 2022-04-13 13:49 UTC by Anatoly230

меню появится из разметки в меню убрать класс  menu--hide

---
:mortar_board: [Адаптивная сетка для главной страницы](https://up.htmlacademy.ru/adaptive/25/user/472465/tasks/7)

:boom: https://htmlacademy-adaptive.github.io/472465-sedona-25/5/

2022-04-14 07:57 UTC, Anatoly230 commented
первичная сетка готова к проверке

2022-04-15 07:57 UTC, ValeryKrukovich requested changes
Появляется полоса прокрутки после 768 px.

2022-04-15 07:57 UTC, ValeryKrukovich commented on source/catalog.html
> +          <a class="menu__item-link menu__item-link-chost" href="№"><span class="visually-hidden">Заглушка</span></a>
А не лучше ли тут menu__item-link-chost сделать модификатором? возможно просто опечатка.

2022-04-15 07:57 UTC, ValeryKrukovich commented on source/sass/blocks/about.scss
> +.aboun__info {
опечатка в названии класса.
Ограничивать по высоте блоки не нужно, может измениться контент и он не поместиться
размер блока делай отступами или минимальной высотой, но не как не четко-ограниченной высотой

2022-04-15 07:57 UTC, ValeryKrukovich commented on source/sass/blocks/info-block.scss
> +  max-height: 300px;
уверен что тут нужно ограничивать высоту? а если контент измениться?

2022-04-15 07:57 UTC, ValeryKrukovich commented on source/sass/blocks/main-footer.scss
> +    height: 120px;
Ограничение высоты - это очень редко используемый и специфичный кейс. уверен что нужно ограничивать высоту?

2022-04-15 09:59 UTC, Anatoly230 commented on source/catalog.html
> +          <a class="menu__item-link menu__item-link-chost" href="№"><span class="visually-hidden">Заглушка</span></a>
Согласен. Класс в принципе лишний, на момент создания не совсем понимал как реализовать призрачный элемент пеню, а когда создал, забыл убрать. Удалил его, он не нужен

2022-04-15 10:14 UTC, Anatoly230 commented on source/sass/blocks/about.scss
> +.aboun__info {
У меня ктсати на эту тему есть вопросы, я не совсем понимаю как правильно оформлять блоки с защитой от переполнения, и задание выполнял согласно рекомендации - не привязываться пока к размерам а делать на глаз.

2022-04-15 10:19 UTC, Anatoly230 commented on source/sass/blocks/info-block.scss
> +  max-height: 300px;
не уверен, не знаю. Подумал что какие-то ограничения быть должны, так как блок наверное не сможет быть бесконечным. Одним словом есть вопросы,хотелось бы обсудить как правильно оформлять текстовые блоки, разделы, блоки-кнопки. 
Жёсткие рамки высоты пока уберу

2022-04-15 19:19 UTC, Anatoly230 commented
Ошибки исправлены

2022-04-16 06:20 UTC, merged